#!/bin/sh
mvn clean package
docker build -t devpatela/GarmentsAppication .
docker rm -f GarmentsAppication 2>/dev/null || true
docker run -it --name GarmentsAppication -p 8080:8080 --name GarmentsAppication devpatela/GarmentsAppication
