#!/bin/sh
mvn clean package
docker build -t devpatel/ClientApplication .
docker rm -f ClientApplication 2>/dev/null || true
docker run -it --name ClientApplication -p 8080:8080 --name ClientApplication devpatel/ClientApplication
